#!/bin/sh
/aesdchar_unload
rmmod aesdchar
module=aesdchar
device=aesdchar
mode="664"
sleep 3
modprobe aesdchar
sleep 3
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo "major is $major"
rm -f /dev/${device}
echo mknod...
mknod /dev/${device} c $major 0
chmod 664 /dev/${device}
#echo "IS IT HERE?"
ls -ll /dev/aesdchar
