#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"
modprobe aesdchar
cd `dirname $0`
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
