#!/bin/sh
cd "/lib/modules/6.1.44/extra"
module="faulty"
module2="scull"
module3="hello"
# Use the same name for the device as the name used for the module

# Support read/write for owner and group, read only for everyone using 644
mode="664"
group="root"

insert_module(){
        echo "LOADING MODULE $module"
        insmod ./$module.ko
        echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
        if [ ! -z ${major} ]; then
                echo "Remove any existing /dev node for /dev/${module}"
                rm -f /dev/${module}
                echo "Add a node for our device at /dev/${module} using mknod"
                mknod /dev/${module} c $major 0
                echo "Change group owner to ${group}"
                chgrp $group /dev/${module}
                echo "Change access mode to ${mode}"
                chmod $mode  /dev/${module}
        else
                echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
        fi
}
insert_module
module=$module2
insert_module
modprobe hello

